/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ABC
 */
import java.awt.*;
import java.sql.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class EmpScreen extends javax.swing.JFrame {

    /**
     * Creates new form EmpScreen
     */
    Connection cn;
    Statement st = null;
    int Global_flg = 0;
    int check = 0;
    public EmpScreen() {
        initComponents();
        setResizable(false);
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
	LocalDate localDate = LocalDate.now();
	String date = dtf.format(localDate);   
        String[] arrofdate=date.split("/",3);
        todaydate.setText(arrofdate[0]+"-"+arrofdate[1]+"-"+arrofdate[2]);
        
        try{
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Project","root","root");
            st = cn.createStatement();
            ResultSet s = st.executeQuery("select Itemname from item");
            com1.addItem("<Select Item>");
            while(s.next()){
                com1.addItem(s.getString(1));
            }
            
        }catch(SQLException e){ 
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        itemstock = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        custBill = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        com1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        citemid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        com2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        crate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ctotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        com3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        ctotalamount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        todaydate = new javax.swing.JTextField();
        buycust = new javax.swing.JButton();
        billcust = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        avlqty = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        seeitem = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("CustBill");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 230, 130, 40);

        itemstock.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        itemstock.setText("Avl Item");
        itemstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemstockActionPerformed(evt);
            }
        });
        jPanel1.add(itemstock);
        itemstock.setBounds(20, 290, 130, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Back to Login...");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 30, 150, 40);

        mainpanel.setPreferredSize(new java.awt.Dimension(800, 765));
        mainpanel.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Item Name");

        com1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        com1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Item ID");

        citemid.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Quantity");

        com2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        com2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        com2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Rate");

        crate.setEditable(false);
        crate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Amount");

        ctotal.setEditable(false);
        ctotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Discount%");

        com3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<%>", "0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));
        com3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        com3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("TotalAmount");

        ctotalamount.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Date");

        todaydate.setEditable(false);

        buycust.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buycust.setText("Buy");
        buycust.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buycust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buycustActionPerformed(evt);
            }
        });

        billcust.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        billcust.setText("Make Bill");
        billcust.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        billcust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billcustActionPerformed(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction Id", "Bill Id", "Item Name", "Item ID", "Quantity taken", "Rate ", "Amount", "Discount", "TotalAmount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Avl Qty");

        avlqty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Remove Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout custBillLayout = new javax.swing.GroupLayout(custBill);
        custBill.setLayout(custBillLayout);
        custBillLayout.setHorizontalGroup(
            custBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custBillLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(custBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(custBillLayout.createSequentialGroup()
                        .addGroup(custBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(custBillLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 649, Short.MAX_VALUE)
                                .addComponent(buycust, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, custBillLayout.createSequentialGroup()
                                .addGroup(custBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ctotalamount, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(billcust, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))
                    .addComponent(jScrollPane1)
                    .addGroup(custBillLayout.createSequentialGroup()
                        .addGroup(custBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(todaydate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(custBillLayout.createSequentialGroup()
                        .addGroup(custBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(custBillLayout.createSequentialGroup()
                                .addComponent(com1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(citemid, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avlqty))
                            .addGroup(custBillLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(custBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(com2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(custBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crate, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(custBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ctotal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(custBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(com3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24))))
        );
        custBillLayout.setVerticalGroup(
            custBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custBillLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(custBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(custBillLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(custBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(custBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(custBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(crate, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(com2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addComponent(avlqty, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(citemid, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(com1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ctotal))
                    .addComponent(com3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(custBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(custBillLayout.createSequentialGroup()
                        .addComponent(todaydate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(ctotalamount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, custBillLayout.createSequentialGroup()
                        .addComponent(buycust, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(custBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(billcust, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
        );

        mainpanel.add(custBill, "card2");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Id", "Item Name", "Remaining Quantity", "Rate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Displaying Item Stock Informatation.........");

        javax.swing.GroupLayout seeitemLayout = new javax.swing.GroupLayout(seeitem);
        seeitem.setLayout(seeitemLayout);
        seeitemLayout.setHorizontalGroup(
            seeitemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(seeitemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
            .addGroup(seeitemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seeitemLayout.createSequentialGroup()
                    .addContainerGap(29, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(84, Short.MAX_VALUE)))
        );
        seeitemLayout.setVerticalGroup(
            seeitemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
            .addGroup(seeitemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seeitemLayout.createSequentialGroup()
                    .addGap(0, 169, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(seeitemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seeitemLayout.createSequentialGroup()
                    .addContainerGap(36, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(665, Short.MAX_VALUE)))
        );

        mainpanel.add(seeitem, "card3");
        mainpanel.add(jLabel12, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void com1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com1ActionPerformed
        com1.setToolTipText("Select Item name");
        if(com1.getSelectedIndex() != 0){
            try{
                cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Project","root","root");
                st = cn.createStatement();
                ResultSet s = st.executeQuery("select Itemid,rate,quantity from item where Itemname = " + "'"+String.valueOf(com1.getSelectedItem())+ "'");s.next();
                citemid.setText(s.getString(1));
                crate.setText(s.getString(2));
                avlqty.setText(s.getString(3));
                com2.addItem("<Quantity>");
                    for(int i=0;i<300;i++)
                        com2.addItem(String.valueOf(i+1));
            }catch(SQLException e){ 
                JOptionPane.showMessageDialog(this,"UNKNOWN ERROR","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_com1ActionPerformed
    int dis = 0;
    private void com3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com3ActionPerformed
        if(ctotal.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Total is Not found");
        }else{
            if(com3.getSelectedIndex() != 0){
                dis = Integer.parseInt((String)com3.getSelectedItem());
                ctotalamount.setText(String.valueOf(Integer.parseInt(ctotal.getText()) - ((Integer.parseInt(ctotal.getText()) * Integer.parseInt((String)com3.getSelectedItem()))/100)));
            }else{
                JOptionPane.showMessageDialog(this,"Please select discount","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_com3ActionPerformed
    int BillId = 0;
    private void billcustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billcustActionPerformed
        if(check == 0){
            JOptionPane.showMessageDialog(this,"Please Buy something before Creating a bill","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                String paidby = "cash";
                ResultSet r = st.executeQuery("select sum(totalamount) from item_trans group by BillId having BillId ="+BillId);r.next();                //discount mean's gst included
                String query = "update item_bill set Billdate='" + todaydate.getText() + "',amount=" + r.getInt(1) +",discount='" + "18%',totalamount=" + (r.getInt(1)+r.getInt(1)*0.18) + ",paidby='" + paidby + "' where BillId=" + BillId;
               PreparedStatement ps = cn.prepareStatement(query);
                ps.execute();
                Global_flg = 0;
                JOptionPane.showMessageDialog(this,"Bill has been Created succesfully");
            }catch(SQLException ex) {
                JOptionPane.showMessageDialog(this,"error ocured while processing","ERROR",JOptionPane.ERROR_MESSAGE);
              
            }
        }
    }//GEN-LAST:event_billcustActionPerformed

    private void com2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com2ActionPerformed
        try {
            ResultSet r = st.executeQuery("select quantity from item where Itemname = " + "'" + (String)com1.getSelectedItem() + "'");r.next();
            if(crate.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"Please Select a Item");
            }else if(com2.getSelectedIndex() != 0){
                if(Integer.parseInt(String.valueOf(com2.getSelectedItem())) > r.getInt(1)){
                    ctotal.setText(null);
                    JOptionPane.showMessageDialog(this,"Chosen Quantity are out of stock");    
                }else{
                    ctotal.setText(String.valueOf(Integer.parseInt(crate.getText()) * Integer.parseInt((String)com2.getSelectedItem())));
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Errot in getting quantity ","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_com2ActionPerformed

    private void buycustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buycustActionPerformed
        if(!(crate.getText().isEmpty() || ctotal.getText().isEmpty() || ctotalamount.getText().isEmpty() )){
            try{
                cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Project","root","root");
                st = cn.createStatement();
                //Entry in BillTable(Do Not Modify)
                if(Global_flg == 0){
                    ResultSet s = st.executeQuery("select max(BillId) from item_bill");s.next();
                    BillId = s.getInt(1) + 1;
                    st.executeUpdate("insert into item_bill(BillId) values (" + BillId + ")");
                    Global_flg = 1;
                }
                //Entry for transaction (Do Not Modify)
                String query = "insert into item_trans(BillId,Item_name,Item_Id,quantity,rate,total,discount,totalamount) values (" + BillId + "," + "'" + (String)com1.getSelectedItem() + "'" + "," + Integer.parseInt(citemid.getText()) + "," + Integer.parseInt((String)com2.getSelectedItem()) + "," + Integer.parseInt(crate.getText()) + "," + Integer.parseInt(ctotal.getText()) + "," + dis + "," +Integer.parseInt(ctotalamount.getText())+")";
                PreparedStatement ps1 = cn.prepareStatement(query);
                ps1.execute();
                // Updating a entries in item table
                query = null;
                query = "update item set quantity=quantity-" + Integer.parseInt(String.valueOf(com2.getSelectedItem())) + " where Itemname =" + "'" + String.valueOf(com1.getSelectedItem()) + "'";
                PreparedStatement ps2 = cn.prepareStatement(query);
                ps2.execute();
                check = 1;
                //Displaying the entry to table1
                ResultSet t = st.executeQuery("select max(TranId) from item_trans");t.next();
                DefaultTableModel model = (DefaultTableModel) table1.getModel();
                model.addRow(new Object[]{t.getInt(1),BillId,(String)com1.getSelectedItem(),citemid.getText(),Integer.parseInt((String)com2.getSelectedItem()),crate.getText(),ctotal.getText(),dis,ctotalamount.getText()});
            }catch(SQLException e){
            }
        }else{
            JOptionPane.showMessageDialog(this,"Please Fill all entries","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buycustActionPerformed

    private void itemstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemstockActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        mainpanel.add(seeitem);
        mainpanel.repaint();
        mainpanel.revalidate();
        try{
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Project","root","root");
            st = cn.createStatement();
            ResultSet s = st.executeQuery("select * from item");
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            while(s.next()){
                model.addRow((new Object[]{s.getString(1),s.getString(2),s.getString(3),s.getString(4)}));
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_itemstockActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();

        mainpanel.add(custBill);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        LoginScreenFinal l = new LoginScreenFinal();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Project","root","root");
            st = cn.createStatement();
            ResultSet s = st.executeQuery("select max(TranId) from item_trans");
            s.next();
            int temp=s.getInt(1);
            st.executeUpdate("delete from item_trans where TranId=" + temp);
            st.executeUpdate("alter table item_trans auto_increment =" + (temp-1));
            DefaultTableModel model = (DefaultTableModel) table1.getModel();
            model.removeRow(model.getRowCount()-1);
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField avlqty;
    private javax.swing.JButton billcust;
    private javax.swing.JButton buycust;
    private javax.swing.JTextField citemid;
    private javax.swing.JComboBox<String> com1;
    private javax.swing.JComboBox<String> com2;
    private javax.swing.JComboBox<String> com3;
    private javax.swing.JTextField crate;
    private javax.swing.JTextField ctotal;
    private javax.swing.JTextField ctotalamount;
    private javax.swing.JPanel custBill;
    private javax.swing.JButton itemstock;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel seeitem;
    private javax.swing.JTable table1;
    private javax.swing.JTextField todaydate;
    // End of variables declaration//GEN-END:variables
}
