/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vaibhav Mahajan
 */
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class LoginScreenFinal extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreenFinal
     */
    public LoginScreenFinal() {
        initComponents();
        setResizable(false);
        lid.setToolTipText("Enter Login Id");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lid = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        pid = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        showpass = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(null);

        lid.setBackground(new java.awt.Color(36, 47, 65));
        lid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lid.setForeground(new java.awt.Color(255, 255, 255));
        lid.setBorder(null);
        jPanel1.add(lid);
        lid.setBounds(640, 170, 330, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(640, 210, 330, 2);

        pid.setBackground(new java.awt.Color(36, 47, 65));
        pid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pid.setForeground(new java.awt.Color(255, 255, 255));
        pid.setBorder(null);
        jPanel1.add(pid);
        pid.setBounds(640, 270, 330, 40);

        login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login);
        login.setBounds(880, 350, 90, 30);

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));
        jPanel2.setMinimumSize(new java.awt.Dimension(510, 601));
        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Wide Latin", 0, 24)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coollogo_com-287951806.gif"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 30, 470, 70);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 510, 600);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(640, 140, 230, 30);

        jLabel2.setBackground(new java.awt.Color(36, 47, 65));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSWORD");
        jLabel2.setMaximumSize(new java.awt.Dimension(78, 22));
        jLabel2.setMinimumSize(new java.awt.Dimension(78, 22));
        jLabel2.setPreferredSize(new java.awt.Dimension(78, 22));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(640, 240, 260, 30);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(640, 310, 330, 2);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password--password-icon-95838edit.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(590, 230, 50, 50);

        showpass.setBackground(new java.awt.Color(36, 47, 65));
        showpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showpass.setForeground(new java.awt.Color(255, 255, 255));
        showpass.setText("Show password");
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        jPanel1.add(showpass);
        showpass.setBounds(640, 350, 180, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-administrator-male-48.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(590, 120, 50, 60);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(584, 234, 50, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        //button code
        Connection cn;
        Statement st;
        int flg=0;
        String role = "manager",role1 = null , role2 = "employee";
        try{
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Project","root","root");
            st = cn.createStatement();
            if(lid.getText().isEmpty()==true){
                JOptionPane.showMessageDialog(this,"Please enter Login Id","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(pid.getText().isEmpty()==true){
                JOptionPane.showMessageDialog(this,"Please enter Password","ERROR",JOptionPane.ERROR_MESSAGE);
            }else{
                ResultSet s = st.executeQuery("select * from user");
                while(s.next()){
                    if(s.getString(1).equals(lid.getText()) && s.getString(8).equals(pid.getText())){
                        //choose role of the user who enter
                        role1 = s.getString(7);
                        JOptionPane.showMessageDialog(this,"Welcome "+s.getString(2));
                        //Entry must be gone into login table
                        st.executeUpdate("insert into login values('"+lid.getText()+"',"+"now())");
                        flg=1;
                        break;
                    }
                }
                if(flg==0){
                    JOptionPane.showMessageDialog(this,"LoginId or password is incorrect","ERROR",JOptionPane.ERROR_MESSAGE);
                }
                //Now opening the frame for manager and a employee
                if(role.equals(role1)){
                    //open frame for manager
                    Close();
                    ManagerScreen ms = new ManagerScreen();
                    ms.setVisible(true);
                }else if(role2.equals(role1)){
                    //open frame for employee
                    Close();
                    EmpScreen ms = new EmpScreen();
                    ms.setVisible(true);
                }
                s.close();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this,e.toString());         
        }  
    }//GEN-LAST:event_loginActionPerformed

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
        if(showpass.isSelected()){
            pid.setEchoChar((char)0);
        }else{
            pid.setEchoChar('*');
        }
    }//GEN-LAST:event_showpassActionPerformed
    public void Close(){
        WindowEvent we = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreenFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreenFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreenFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreenFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreenFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField lid;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField pid;
    private javax.swing.JCheckBox showpass;
    // End of variables declaration//GEN-END:variables
}
